### ISSUE TITLE
Request for information not an issue

### ISSUE THREAD

**Issue by sblakegit** [SilverFire/esp8266-pc-power-control#1]
I am interested in doing similar with a WemosD1 (<£4 on amazon) which includes about 98% of the components already.  I want to make sure that i do not fry my motherboard.  Many others have used transistors or optoisolators or even relays to interface with the PC motherboard pins.  Your solution is very tidy.  I was wondering how you calculated the 20k resistors and your thinking behind them.  Steve

**Comment by SilverFire** [comment]
Hello. I'm not an electronics guru, but here are my thoughts:

> I want to make sure that i do not fry my motherboard

Mine works fine for almost one year :)

> Many others have used transistors or optoisolators or even relays to interface with the PC motherboard pins.

Transistors can commutate high currents on Emitter-Collector transition by applying low current to the Base. Relays do nearly the same mechanically, but also provide isolation. Optocouplers are about isolation only. All of them are overkill for some reasons: I neither need to commutate high currents, nor care about isolation. Since my ESP8266 is powered from the motherboard, in case I have something wrong with ESP8266 power it should NOT harm motherboard because I assume motherboard will be already dead (otherwise why it should give me wrong voltage?).

> I was wondering how you calculated the 20k resistors

Just a random value based on experience.

**Comment by sblakegit** [comment]
Thanks for speedy response.
My understanding was that the PC TTL output was 5V and that there was potential for the ESP8266 pins to see 5V.  It appeared that if this occurred there was scope for terminating the ESP.  I was nervous that in the process the motherboard could be terminated.  You have a point though, if the motherboard is happy with 5V and the esp is powered from 5V how can the motherboard be fried.

**Comment by SilverFire** [comment]
You're welcome. I will be happy to know about your experience in implementing such a device
